version: "3.8"

services:
  frontend:
    container_name: 'nextjs-frontend'
    build:
      context: ./nextjs-frontend
      dockerfile: dockerfile.prod
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
        NEXT_PUBLIC_API_URL: ${API_URL}
    restart: always
    ports:
      - 3000:3000
      
  api:
    container_name: 'dotnet-webapi'
    build:
      context: ./dotnet-webapi/
      dockerfile: dockerfile 
    environment:
      IN_DOCKER: true
    depends_on:
      - db
    ports:
      - 5000:5000
      - 5001:5001
    networks:
      - my_network
    extra_hosts:
      # Needed on linux server
      - host.docker.internal:host-gateway

  db:
    container_name: 'postgres'
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - my_network


networks:
  my_network:
    name: dotnetpg-network
    driver: bridge